version: "3.9"
services:
  android-emulator-1:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5554:5554
      - 5555:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_1:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-1
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m

  android-emulator-2:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5553:5554
      - 5552:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_2:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-2
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m
    depends_on:
      android-emulator-1:
        condition: "service_healthy"

  android-emulator-3:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5551:5554
      - 5550:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_3:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-3
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m
    depends_on:
      android-emulator-2:
        condition: "service_healthy"

  android-emulator-4:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5549:5554
      - 5548:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_4:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-4
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m
    depends_on:
      android-emulator-3:
        condition: "service_healthy"
  android-emulator-5:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5547:5554
      - 5546:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_5:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-5
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m
    depends_on:
      android-emulator-4:
        condition: "service_healthy"
  android-emulator-6:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5545:5554
      - 5544:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_6:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-6
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m
    depends_on:
      android-emulator-5:
        condition: "service_healthy"
  android-emulator-7:
    mem_limit: 4g
    build:
      context: ./docker-android
    ports:
      - 5543:5554
      - 5542:5555
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./docker-android/keys/adbkey:/root/.android/adbkey:ro
      - ./docker-android/keys/adbkey.pub:/root/.android/adbkey.pub:ro
      - ./docker-android/android_avd_7:/data
    devices:
      - /dev/kvm:/dev/kvm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - android-net
    hostname: android-emulator-7
    healthcheck:
      test: [ "CMD", "adb", "wait-for-device" ]
      interval: 5m
      timeout: 10s
      retries: 10
      start_period: 5m
    depends_on:
      android-emulator-6:
        condition: "service_healthy"

  frida-service:
    mem_limit: 2g
    build:
      context: ./frida-service
    ports:
      - 3000:3000
    depends_on:
      android-emulator-1:
        condition: "service_healthy"
      android-emulator-2:
        condition: "service_healthy"
      android-emulator-3:
        condition: "service_healthy"
      android-emulator-4:
        condition: "service_healthy"
      android-emulator-5:
        condition: "service_healthy"
      android-emulator-6:
        condition: "service_healthy"
      android-emulator-7:
        condition: "service_healthy"
    networks:
      - android-net

networks:
  android-net:
    driver: bridge
